services:
  - type: web
    buildCommand: |
      cd src  # Change to the directory where your React app is located
      npm install  # Install npm dependencies
      npm run build  # Build the React app
    startCommand: cd src && npm start

  - type: web
    buildCommand: |
      python -m venv venv  # Create a virtual environment for Python
      source venv/bin/activate  # Activate the virtual environment (use 'venv\Scripts\activate' on Windows)
      pip install -r requirements.txt  # Install Python dependencies
    startCommand: python back/server.py  # Start the Python backend using Gunicorn
